export const ERR_CLIENT_NOT_FOUND = "CLIENT_NOT_FOUND";
export const ERR_INVOICE_NOT_FOUND = "INVOICE_NOT_FOUND";
export const ERR_PDF_NOT_READY = "PDF_NOT_READY";
export const ERR_INVALID_PAYLOAD = "INVALID_PAYLOAD";
